Feat:  Site Journey
DEFRA/wildlife-licencing pull request #160
Opened 2022-11-08 17:47 UTC by byohannes

2022-11-10 15:18 UTC, GrahamMWillis requested changes
Looks really good, just a couple of comments

2022-11-10 15:18 UTC, GrahamMWillis commented on packages/web-service/src/pages/site/site-got-postcode/site-got-postcode.js
> +  // await request.cache().clearPageData(siteURIs.SITE_GOT_POSTCODE.page)
Remove the comment please

2022-11-10 15:18 UTC, GrahamMWillis commented on packages/web-service/src/pages/site/site-got-postcode/site-got-postcode.js
> +  const { siteData } = (await request.cache().getData())
Why the ()?

2022-11-10 15:18 UTC, GrahamMWillis commented on packages/web-service/src/pages/site/site-got-postcode/site-got-postcode.js
> +    'site-postcode': Joi.string().trim().min(1).max(12).required().pattern(ukPostcodeRegex)
I think the max UK postcode length is 7 characters (excluding the ' ') however I think the regex handles this so you can probably just remove the min, max and ensure the text entry is just long enough

2022-11-10 15:18 UTC, GrahamMWillis commented on packages/web-service/src/pages/site/site-got-postcode/site-got-postcode.njk
> +  {{ govukRadios({
Indentation

2022-11-10 15:18 UTC, GrahamMWillis commented on packages/web-service/src/pages/supporting-information/check-supporting-information.njk
> +                text: "Do you want to upload another file ?" if data.length > 0 else "Do you want to upload a supporting information file ?" ,
Do you really want a space here?

2022-11-10 18:16 UTC, byohannes commented on packages/web-service/src/pages/site/site-check/site-check.js
> +const siteAddressLine1 = c => [
moved the address. to a service directory to be accessed commonly across other pages

2022-11-10 18:17 UTC, byohannes commented on packages/web-service/src/pages/site/site-got-postcode/site-got-postcode.js
> +  // await request.cache().clearPageData(siteURIs.SITE_GOT_POSTCODE.page)
removed the commented code

2022-11-14 12:38 UTC, kealanparr commented on packages/web-service/src/__tests__/additional-page-data.spec.js
> +        siteMapTwo: '/upload-map-2',
`upload-map-2`, `upload-map-2` - can we rename it to something more descriptive?

2022-11-14 12:55 UTC, kealanparr commented on packages/web-service/src/__tests__/additional-page-data.spec.js
> +        siteMapTwo: '/upload-map-2',
Please make sure the `CONFIRMED_NOT_COMPLETE` handler works too :) Just had a quick Slack call we need to go back to CYA page, if you complete the flow but don't submit the answers

2022-11-14 12:56 UTC, kealanparr submitted a review, later dismissed
Comments left inline to please fix :)

2022-11-14 13:10 UTC, GrahamMWillis approved these changes

2022-11-14 15:15 UTC, byohannes commented on packages/web-service/src/pages/site/site-got-postcode/site-got-postcode.js
> +  const { siteData } = (await request.cache().getData())
removed the brackets

2022-11-14 15:16 UTC, kealanparr approved these changes

2022-11-14 15:21 UTC, kealanparr approved these changes

2022-11-14 15:21 UTC, merged