style: SDDSIP-2058 - Sequelize config file added
DEFRA/wildlife-licencing pull request #620
Opened 2024-02-13 11:00 UTC by richard-mohammed-def

https://eaflood.atlassian.net/browse/SDDSIP-2058?focusedCommentId=574947

2024-02-13 13:48 UTC, StuAA78 requested changes
Nice one, just a couple of small tweaks requested but hopefully this will fix it!

2024-02-13 13:48 UTC, StuAA78 commented on packages/api/sequelize.config.cjs
> +  development: {
I just checked and all our environments have been configured with `NODE_ENV` set to `production`. So this key needs to be named `production` for it to work in the environments. However it doesn't strike me as ideal that we have dev and test environments set as `production`! So for now, can this object also include `development` and `test` (with the same values). Then we're covered if in future we change `NODE_ENV` to more suitable values.

2024-02-13 13:48 UTC, StuAA78 commented on packages/api/sequelize.config.cjs
> +    host: process.env.POSTGRES_HOST,
Can we also add `port: process.env.POSTGRES_PORT` to this. I can't imagine we would set it to anything other than the default port `5432` but we do set it in the environment so we ought to use it here as well.

2024-02-13 16:35 UTC, jonathangoulding approved these changes

2024-02-14 10:07 UTC, StuAA78 approved these changes
Great stuff 👍

2024-02-14 10:08 UTC, merged