Feature: ClamScan container config and scan file.
DEFRA/wildlife-licencing pull request #71
Opened 2022-07-07 09:08 UTC by sfaulkner89

2022-07-08 10:04 UTC, GrahamMWillis requested changes

2022-07-08 10:04 UTC, GrahamMWillis commented on packages/web-service/src/services/virus-scan.js
> +      const dir = `../..${process.env.SCANDIR}/${filename}`
This needs to be an absolute path I think

2022-07-08 10:04 UTC, GrahamMWillis commented on docker/cloud-services.yml
> +  scandir:
Not a big deal but the convention is a CR at the EOF

2022-07-08 13:45 UTC, sfaulkner89 commented
After talking to Kealan we decided that if the scan fails, the file should be deleted on my end for consistency's sake. I've added that in, fixed your comments and the code smells.

2022-07-11 07:06 UTC, GrahamMWillis requested changes

2022-07-11 07:06 UTC, GrahamMWillis commented on packages/web-service/src/services/virus-scan.js
> +  const dir = `.${process.env.SCANDIR}/${filename}`
I still think this should be an absolute path - do you want to have a chat about it?

2022-07-11 12:40 UTC, merged